//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoLenguajesMMDS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Answer
    {
        public int Answer_id { get; set; }
        public Nullable<int> Query_id { get; set; }
        public string Answer1 { get; set; }
        public string Type { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<int> Person_id { get; set; }
        public Nullable<int> Course_id { get; set; }
        public Nullable<int> Created_by { get; set; }
        public Nullable<System.DateTime> Create_at { get; set; }
        public Nullable<int> Updated_by { get; set; }
        public Nullable<System.DateTime> Updated_at { get; set; }
    
        public virtual Person Person { get; set; }
        public virtual Person Person1 { get; set; }
        public virtual Query Query { get; set; }
        public virtual Person Person2 { get; set; }
    }
}
