//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoLenguajesMMDS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Appointment
    {
        public int Appointment_id { get; set; }
        public int Professor_course_id { get; set; }
        public int Student_id { get; set; }
        public string Start_hour { get; set; }
        public string End_hour { get; set; }
        public string Day { get; set; }
        public Nullable<int> Created_by { get; set; }
        public Nullable<System.DateTime> Create_at { get; set; }
        public Nullable<int> Updated_by { get; set; }
        public Nullable<System.DateTime> Updated_at { get; set; }
        public string Status { get; set; }
    
        public virtual Person Person { get; set; }
        public virtual Professor_Course Professor_Course { get; set; }
        public virtual Student Student { get; set; }
        public virtual Person Person1 { get; set; }
    }
}
