//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoLenguajesMMDS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Office_Hours
    {
        public int Office_hours_id { get; set; }
        public string Day { get; set; }
        public string Start_hour { get; set; }
        public string End_hour { get; set; }
        public Nullable<int> Professor_course_id { get; set; }
    
        public virtual Professor_Course Professor_Course { get; set; }
    }
}
