//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoLenguajesMMDS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Person_Social_Network
    {
        public int Social_network_id { get; set; }
        public int Person_id { get; set; }
        public string URL { get; set; }
    
        public virtual Person Person { get; set; }
        public virtual Social_Network Social_Network { get; set; }
    }
}
